---  

- name: start virtual machines
  tags: start
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    name: "{{ item }}"
    state: started
    timeout: 1800
  with_items: "{{ vm_names }}"
  no_log: False

- name: stop virtual machines
  tags: stop
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    name: "{{ item }}"
    state: stopped
    timeout: 1800
  with_items: "{{ vm_names }}"
  no_log: False
  
- name: remove virtual machines
  tags: remove
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    name: "{{ item }}"
    state: absent
    timeout: 1800
  with_items: "{{ vm_names }}"
  no_log: False
  
- name: restart virtual machines
  tags: restart
  proxmox_kvm:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    node: "{{ proxmox_node }}"
    name: "{{ item }}"
    state: restarted
    timeout: 1800
  with_items: "{{ vm_names }}"
  no_log: Falses