---  

- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - slapd
    - ldap-utils
    - python-ldap
    
- name: Start ldap service
  service:
    name: slapd
    state: started
    
- name: Register encripted password
  command: slappasswd -s "{{ldap_auth.bind_pw}}"
  register: ldap_encripted_password
  
- name: Copy db templates
  template:
    src: db.ldif
    dest: /tmp
    
- name: Load ddbb template into ldap
  command: ldapmodify -Y EXTERNAL  -H ldapi:/// -f /tmp/db.ldif
    
- name: Load ldap root entry
  ldap_entry:
    params: "{{ldap_auth}}"
    dn: "{{ldap_basedn}}"
    objectClass:
      - top
      - domain
      
- name: Load groups and users parent entry
  ldap_entry:
    params: "{{ldap_auth}}"
    dn: "ou={{item}},{{ldap_basedn}}"
    objectClass:
      - organizationalUnit
      - top
  with_items:
    - groups
    - people
    
- name: Load users
  ldap_entry:
    params: "{{ldap_auth}}"
    dn: "cn={{item.value.cn}},ou=people,{{ldap_basedn}}"
    objectClass:
      - person
      - organizationalPerson
      - inetOrgPerson
      - top
    attributes:
      cn: "{{item.value.cn}}"
      givenname: "{{item.value.givenname}}"
      sn: "{{item.value.sn}}"
      uid: "{{item.key}}"
      mail: "{{item.value.mail}}"
      userpassword: "{{item.value.userpassword}}"
      #employeeNumber: "{{item.value.employeeNumber}}"
  with_dict: "{{ldap_users}}"
  
  - name: Load groups
  ldap_entry:
    params: "{{ldap_auth}}"
    dn: "cn={{item.name}},ou=groups,{{ldap_basedn}}"
    objectClass:
      - groupOfUniqueNames
      - top
    attributes:
      uniqueMember: "uid=dummy,ou=people,{{ldap_basedn}}"
  with_items: "{{ldap_groups}}"

- name: Add users to groups
  ldap_attr:
    params: "{{ldap_auth}}"
    dn: "cn={{item.0.name}},ou=groups,{{ldap_basedn}}"
    name: uniqueMember
    values: "uid={{item.1}},ou=people,{{ldap_basedn}}"
    state: present
  with_subelements:
    - "{{ldap_groups}}"
    - members
    
- name: Restart ldap service
  service:
    name: slapd
    state: restarted
© 2018 GitHub, Inc.