---

- name: Apply the common role to the dev group
  hosts: authentication
  roles:
   - common
  tags: common
  
- name: Apply the phpldapadmin role to the dev group
  hosts: authentication
  roles:
    - mrlesmithjr.etc-hosts
    - mrlesmithjr.openldap
 