---

- name: Apply the common role to the authentication group
  hosts: authentication
  roles:
   - common
  tags: common
  
- name: Apply the openldap role to the authentication group
  hosts: authentication
  roles:
    - openldap
  tags: openldap
  
# - name: Apply the kerberos role to the authentication group
  # hosts: authentication
  # roles:
    # - kerberos
  # tags: kerberos
 