---
- hosts: new-nodes 
  gather_facts: True
  remote_user: root

  vars: 
    packages: [sudo, aptitude, emacs, rsync, sudo, mercurial, ssh, git, htop, curl, figlet]
  tasks:

    - name: update
      apt: update_cache=yes
      
    - name: install 
      apt: name= '{{ packages }}' state=present
        
    - name: create user
      user: 
        name: 
        shell: /bin/bash
        password: hadoop
        groups: sudo
        append: yes
        #sudo pip install passlib
        #python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.using(rounds=5000).hash(getpass.getpass())"

    - name: create dir
      file:
        path: /home/evens/.ssh
        state: directory
        owner: evens
        group: evens
        mode: 0755

    - name: copy authorized_keys
      copy:
        src: "{{ playbook_dir }}/files/authorized_keys"
        dest: /home/evens/.ssh/authorized_keys
        owner: evens
        group: evens
        mode: 0600

    - name: copy bashrc file
      copy: src={{ playbook_dir }}/files/bashrc-work dest=/home/evens/.bashrc owner=evens group=evens mode=0600

    - debug: 
        msg: "{{ ansible_hostname }} {{ ansible_distribution_release }} {{ ansible_default_ipv4.address }}"
