---

webofmars.xfce4-desktop

- name: Apply the webofmars role to the dev group
  hosts: dev
  roles:
   - webofmars.xfce4-desktop
  tags: webofmars.xfce4-desktop
  
- name: Apply the common role to the dev group
  hosts: dev
  roles:
   - common
  tags: common
  
- name: Apply the gantsign.intellij role to the dev group
  hosts: dev
  roles:
   - gantsign.intellij
  tags: intellij 
 
- name: Apply the geerlingguy.git role to the dev group
  hosts: dev
  roles:
   - geerlingguy.git
  tags: git  
  
- name: Apply the sdarwin.vnc role to the dev group
  hosts: dev
  roles:
   - sdarwin.vnc
  tags: vnc
 