---
# vm definitions example
vms:
  ubuntu-cloud-init-1:
    cloudinit: true
    memory_size: '8192'
    cores       : '1'
    vcores       : '4'
    template: 'cloudinit-ubuntu-template'
    node: 'pve'
    ipconfig: '{"ipconfig0":"ip=192.168.1.101/24,gw=192.168.1.1"}'
    sshkeys: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsvTnk0heb3C7DGvVE2gd0kRtQQYkIk+hEtSJeizlF5MuAX+O7NXDIBmUP1F2MnjtwBCs8MMlmteWR02PaVw0CvuKZqDN9CK59EYeIk7yzyEYMsGwf7sqNHZfqSI+apcohDOMXGcURTf6BymOe7AhzE+0TRX98li3wXHuDSnTSU84NHNgOTm2YxOPXgiCLE5YlhdAc3uEkBN2TOjkYBmhNmwqpLJEAaV60xF9HwROkEl15+K4ha1khbnCcqHJhV1iDEfrEb8psTLdBHrdtUamQAotJjFCUkDxVKWiykR77NtI2uxOOjN212kijoGnM+uyt78Hn6rlko7xp7lLfOBNH isancmen@everis.com'
    timeout: '1800'