---
# default clone values
defaults:
  cpu: "host"
  user: "ubuntu1"
  net: '{"net0":"virtio,bridge=vmbr0"}'
  cores: '2'
  vcores: '2'
  memory_size: '2048'
  balloon: '1024'
  scsihw: 'virtio-scsi-pci'
  virtio: '{"scsi0":"local-zfs:16,cache=writeback,discard=on"}'
  ipconfig: '{"ipconfig0":"ip=192.168.1.111/24,gw=192.168.1.1"}'
  ostype: 'l26'
#  sshkeys: 'ssh-rsa..AAABBBZZZ'
