---

- name: Install kerberos packages
  yum:
    name: "{{ item }}"
    install_recommends: no 
    state: present
  with_items: "{{ centos_pkg }}"
  when: ansible_facts['os_family'] == "CentOS"
  
- name: Install kerberos packages
  apt:
    name: "{{ item }}"
    install_recommends: no 
    state: present
  with_items: "{{ ubuntu_pkg }}"
  when: ansible_facts['os_family'] == "Debian"
  
- name: Copy the client configuration file 
  template: src=krb5.conf.j2 dest=/etc/krb5.conf


