---  

- name: Install required packages
  package:
    name: "{{ item }}"
    update_cache: no
    state: present
  with_items: "{{ packages | join(',') }}"
  
- name: Install Java
  include_tasks: java.yml